PROCESS_DATA_CONFIG:
  DATA_FOLDER: data
  FILE_NAME: iris_data.csv

MODEL_ARTIFACTS_PATH_PREFIX: /opt/ml/

INPUT_LOCATION: input/data/

CONFIG_LOCATION: input/config/

HYPERPARMETER_FILE_NAME: hyperparameters.json

OUTPUT_LOCATION: output

MODEL_LOCATION: model/

DATA_CHECKPOINT_PATH: /data/data_checkpoints/

TRAINING_CHANNEL_NAME: training
