
DATA_FOLDER: ../data/data_files/


RACES_DF_COLUMNS_FOR_MERGE: 
  - raceId
  - year
  - round
  - circuitId
  - name
  - date

RESULTS_DF_COLUMNS_FOR_MERGE:
  - raceId
  - driverId
  - number
  - statusId

PIT_STOP_DF_COLUMNS_FOR_MERGE:
  - raceId
  - driverId
  - lap
  - pitStopMilliseconds
