
DATA_FOLDER: ../data/data_files/


RACES_DF_COLUMNS_FOR_MERGE: 
  - raceId
  - year
  - round
  - circuitId
  - name
  - date

RESULTS_DF_COLUMNS_FOR_MERGE:
  - raceId
  - driverId
  - number
  - statusId

PIT_STOP_DF_COLUMNS_FOR_MERGE:
  - raceId
  - driverId
  - lap
  - pitStopMilliseconds

FEATURE_USED_IN_TRAINING:
  - raceId
  - lap
  - position
  - milliseconds
  - circuitId
  - year
  - date
  - isPitStop
  - pitStopMilliseconds

FEATURES_TO_ONEHOT_ENCODE:
  - circuitId

LAGGED_FEATURES:
  - milliseconds
  - lap
  - position
  - pitStopMilliseconds
  - isPitStop

DROP_COLUMNS_AVOID_LEAKAGE:
  - position
  - isPitStop
  - pitStopMilliseconds

RACE_ID_TEST_SET: 867

NUMBER_OF_HISTORICAL_LAP: 5

MINIMUM_LAPS_IN_GP: 8

MINMAX_SCALING_COLUMNS:
  - lap
  - lap_number_1_prior
  - position_1_prior_lap
  - pitStopMilliseconds_1_prior

ROBUST_SCALING:
  - milliseconds_1_prior

TARGET_COLUMN: milliseconds

HIDDEN_SIZE_1: 48

HIDDEN_SIZE_2: 32

DENSE_LAYER: 16 

BATCH_SIZE: 8

MODEL_PATH: ../artifacts/

NUM_LAYERS: 1

N_STEP_OUTPUT: 5