
DATA_FOLDER: ../data/data_files/


RACES_DF_COLUMNS_FOR_MERGE: 
  - raceId
  - year
  - round
  - circuitId
  - name
  - date

RESULTS_DF_COLUMNS_FOR_MERGE:
  - raceId
  - driverId
  - number
  - statusId

PIT_STOP_DF_COLUMNS_FOR_MERGE:
  - raceId
  - driverId
  - lap
  - pitStopMilliseconds

FEATURE_USED_IN_TRAINING:
  - raceId
  - lap
  - position
  - milliseconds
  - year
  - date
  - statusId
  - isPitStop

FEATURES_TO_ONEHOT_ENCODE: 
  - isPitStop
  - statusId

MINIMUM_LAPS_IN_GP: 8

MINMAX_SCALING_COLUMNS:
  - lap
  - position
  - milliseconds_1_prior
  - lap_number_1_prior
  - position_1_prior_lap

TARGET_COLUMN: milliseconds

MODEL_PATH: ../artifacts/

INPUT_SIZE: 54

NUM_LAYERS: 1

NUM_CLASSES: 5